name: gradle-dependency-submission

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
        gradle-home-cache-excludes: dependency-check-data
    - name: gradle-dependency-submission
      uses: mikepenz/gradle-dependency-submission@v0.8.5
      with:
        use-gradlew: true
        gradle-build-module: |-
          :
        gradle-build-configuration: |-
          compileClasspath
      env:
        JDK_JAVA_OPTIONS: -Dpolyglot.engine.WarnInterpreterOnly=false